### ISSUE TITLE
Testing URL

### ISSUE THREAD

**Issue by yarekc** [akshat7101999/WebRTC-scalable-broadcast-p2p#2]
Hi,
Would be great if you could publish a demo so people can test the concept.
Regards

**Comment by akshat7101999** [comment]
Hello,
What do you exactly mean by publish a demo.... where should i publish it ? Weren't you able to successfully run the code ?

**Comment by yarekc** [comment]
Hi,
Well.. I have not even tried to install it because I would like to test it before.
It is always a pain to install some certificates,  setup node environment on Windows..
Would be really great to have an online demo. I have no idea if this is a simple proof of concept or this is suitable to production.

**Comment by akshat7101999** [comment]
The certificate has been generated already. Since as additional security in new versions of browsers, webRTC works on https only so the certificate is necessary. You don't need to install it separately. The web-app is quite easy to use. I have detailed the instructions in Readme file. Just follow those and it will work fine. I will think about uploading a demo also. Thanks for the suggestion !!
